// Generated by CoffeeScript 1.4.0
var updatePanel;

updatePanel = function() {
  return console.log($('#election-panel li[class=active]').text());
};

jQuery(function() {
  return updatePanel();
});
