// Generated by CoffeeScript 1.4.0
var updateOrganizationInformation;

jQuery(function() {
  return $('#updateProfile').click(updateOrganizationInformation);
});

updateOrganizationInformation = function() {
  var postData;
  postData = {
    'id': $('#organization-id').val(),
    'name': $('#organization-name').val(),
    'description': $('#organization-description').val(),
    'website': $('#organization-website').val()
  };
  console.log(postData);
  return $.ajax({
    url: '/organization-panel',
    type: 'POST',
    data: {
      'data': JSON.stringify(postData)
    },
    success: function(data) {
      console.log('Success!');
      console.log(data);
      return $('#election-information').append(data);
    },
    error: function(data) {
      console.log('Error...');
      return console.log(data);
    }
  });
};
