// Generated by CoffeeScript 1.4.0
var errorHandler, successHandler, updateOrganizationInformation;

jQuery(function() {
  return $('#updateProfile').click(function(event) {
    return updateOrganizationInformation(event);
  });
});

updateOrganizationInformation = function(event) {
  var postData;
  event.preventDefault();
  postData = {
    'id': $('#organization-id').val(),
    'name': $('#organization-name').val(),
    'description': $('#organization-description').val(),
    'website': $('#organization-website').val()
  };
  console.log(postData);
  return $.ajax({
    url: '/organization-panel',
    type: 'POST',
    data: {
      'data': JSON.stringify(postData)
    },
    success: function(data) {
      return successHandler(data);
    },
    error: function(data) {
      return errorHandler(data);
    }
  });
};

successHandler = function(data) {
  var s;
  s = $('#server-response');
  s.append('Succesfully updated your ogranization profile');
  s.addClass('alert');
  s.addClass('alert-success');
  return s.show();
};

errorHandler = function(data) {
  var s;
  s = $('#server-response');
  s.append('Sorry, there was a server error.');
  s.addClass('alert');
  s.addClass('alert-error');
  return s.show();
};
