application: owlection
version: angular
module: default
runtime: python27
api_version: 1
threadsafe: yes

instance_class: F1

default_expiration: "10s"

libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2
  version: latest

builtins:
- remote_api: on

inbound_services:
- warmup

error_handlers:
  - error_code: over_quota
    file: views/full_outage.html

handlers:

- url: /static
  static_dir: static

- url: /admin/.*
  script: controllers.admin.app

- url: /vote.*
  script: controllers.vote.app

- url: /authenticate/.*
  script: controllers.authenticate.app

- url: /intern/.*
  script: controllers.intern.app

- url: /tasks/.*
  script: controllers.tasks.app
  login: admin

#- url: /.*
#  script: main.app
##
# Angular Settings
- url: /api/.*
  script: controllers.api.app

- url: /(.*\.(gif|png|jpeg|jpg|css|js|ico))$
  static_files: static/dist/\1
  upload: static/dist/(.*)

- url: /(.*)
  static_files: static/dist/index.html
  upload: static/dist/index.html